language: java
jdk:
  - oraclejdk11
deploy:
  provider: heroku
  api_key:
    secure: P4n5/Ti1Irbdvf7BHkCp+2n3Z//kaH3bS/EkwcbsMhB3S4t35FOV5w1itKfxOg5ZF2TFijt2Ddrw+LfHUMkM6Xg7GQNCjf0XIlE6fFzyaXYe8CmDt/eeLDvQhsTPUuAH4GgSfiMY4pmjteW778VtWn4WzcoJqY1e8EErcoBDwIPrNwTSIxoiL1CVEyYXns9ZCzR4JEtsdqcRek4uA08HYjd5W94SLrR4iDT22VEJJ3zZKYBhbGQe63svG1bFx0KIWQWzfARXePoQJtYTF9zI5KMa6d0gPh4VM5zpNQ8KDz5/RK8P6cke7+eUyVUThTY1JBWRMGymZ/XmGN0Enno35hPvFSU/wVoFFqVijZwNYsX5QdyE0yAszFSzGQmdns0Z+GJhY6VzJKpkFUNsTw7N8Jk+OFSF3rZYZt3cJ1isTspLC2NPFHDCcLcer8TtunQ+AFV8Btxoq5sFyv+UMeUW883gJIpiSCs0TtlV2YXXTodfXx3PeSCk95CNn+aJ8SlbtbDGL4KSt6xborcayDdy/DTaF4JvVM6kTve8YcU22zF7Nn3POuswVBwVY2FuHhfO4RtS5DCZoMmcHZO7+Nh4s7N0i4/rtVlYpZTicNM0+x/7EnEmdAyAXPqT8maI7p5Rylj7KArxD4ewJ7y1PN3QXtqeFpwBoVZnRkNknCFx39o=
  app: regex-gen
before_install:
  - chmod +x mvnw